parliament/statement.py, tests/unit/test_patterns.py
I noticed inconsistent output for certain actions vs others (`service:Action` in some cases, `service.Action` in others) => 
```
INVALID - No resources match for s3.CreateJob which requires a resource format of * - {'filepath': None}
INVALID - No resources match for s3:DescribeJob which requires a resource format of arn:*:s3:*:*:job/* for the resource job* - {'filepath': None}
INVALID - No resources match for s3.GetAccountPublicAccessBlock which requires a resource format of * - {'filepath': None}
INVALID - No resources match for s3.ListAllMyBuckets which requires a resource format of * - {'filepath': None}
INVALID - No resources match for s3.ListJobs which requires a resource format of * - {'filepath': None}
INVALID - No resources match for s3.PutAccountPublicAccessBlock which requires a …
```
=> Make service and action display format consistent

parliament/statement.py
Seems like no real harm as currently coded, but good to fix the typo anyway :)
=> Fix typo "resouces" => resources

.gitignore, .travis.yml, Makefile, README.md, requirements.txt
Hey @0xdabbad00,
Here's a PR that aims to add TravisCI integration for parliament.
Specifically, I've created a requirements.txt file by creating a new venv, installing the requirements you listed, then `pip freeze > requirements.txt` so that only those requirements and their dependencies are included.
I've created a .travis.yml file which tells Travis CI to install the requirements and run the tests for both Python 3.7 and 3.8. More information can be found [here](https://docs.travis-ci.com/user/languages/python/).
Finally, I created a Makefile to make installation and testing easier. Note that I adjusted it to use the standard environment since we're already telling folks to use a venv in the readme. I then updated the README to match the new changes.
I can't guarantee this will work …
=> Created requirements.txt file and added Travis CI integration

README.md
I integrated Parliament as a library into Paco. One of Paco's goals is to validate and verify as much configuration as it can before it actually goes and makes changes to AWS. This library works great for helping with that :)
=> add note about Paco using Parliament

setup.py
This PR fixes #90 as latest published version of parliament misses config_override.yaml from parliament/community_auditors directory.
Output from `python setup.py sdist`:
```
running sdist
running egg_info
writing parliament.egg-info/PKG-INFO
writing dependency_links to parliament.egg-info/dependency_links.txt
writing entry points to parliament.egg-info/entry_points.txt
writing requirements to parliament.egg-info/requires.txt
writing top-level names to parliament.egg-info/top_level.txt
reading manifest file 'parliament.egg-info/SOURCES.txt'
writing manifest file 'parliament.egg-info/SOURCES.txt'
running check
creating parliament-0.4.8
creating parliament-0.4.8/parliament
creating parliament-0.4.8/parliament.egg-info
creating parliament-0.4.8/parliament/community_auditors
copying files to …
```
=> Ship config_override.yaml from parliament/community_auditors

.github/workflows/publish.yml
Adds a GitHub Actions workflow which creates new PyPI releases automatically anytime a new GitHub release is created.
Note to @0xdabbad00 - we can wait until we confirm that the same workflow is working for Cloudtracker before merging this in.
=> Setup Automatic PyPI Deployments

parliament/__init__.py
I noticed that parliament's analysis is very slow on policies with many actions, profiling showed that the function `expand_action` is called millions of times with the same arguments. I added `lru_cache` for the function it resulted in a great improvement from ~20 seconds to ~110ms on my machine.
I thought it would be useful for all.
Here's how to reproduce the issue:
```python
from parliament import Policy
policy_doc = {
"Statement": [
{
"Action": [
"autoscaling:CreateOrUpdateTags",
"autoscaling:DeleteAutoScalingGroup",
"autoscaling:DeleteLaunchConfiguration",
"autoscaling:DeleteTags",
"autoscaling:DescribeLaunchConfigurations",
"autoscaling:ResumeProcesses",
"autoscaling:SuspendProcesses",
"autoscaling:UpdateAutoScalingGroup",
"cloudWatch:PutMetricData", …
```
=> performance: making parliament 100 times faster on long policies

parliament/statement.py, tests/unit/test_resources.py
Parliament fails with an AttributeError when analyzing a policy with this resource: `{"Fn::Sub": "arn:aws:ssm:*:${AWS::AccountId}:*"}`.
From the linked issue:
> Having a more helpful error message here and avoiding Parliament from crashing would be good though.
This PR tries to provide that. :)
Closes duo-labs/parliament#120
=> Gracefully handle resources with cloudformation concepts

parliament/statement.py
This removes the tons of duplicate RESOURCE_STAR findings that occur when a statement has multiple actions and when wildcard actions get expanded.  I have had instances with hundreds of this finding for the same statement.
=> Only report RESOURCE_STAR finding once per statement

parliament/cli.py
This PR fixes the  logic used to ignore AWS defined policies
=> Fix logic used to ignore AWS defined policies when parsing AWS Auth Details File

README.md
This just adds a link to a demo web app I made that uses Parliament.  That site is associated with Summit Route.
@kylelady @jordan-wright This is ready to be merged.
=> Add demo web app link to README

parliament/statement.py
This fixes the error encountered when trying to run parliament on a PowerUsers-esque policy (assumedly any policy with a NotAction):
```
{
"Statement": [
{
"NotAction": "iam:*",
"Effect": "Allow",
"Resource": "*"
},
],
"Version": "2012-10-17"
}
```
```
FOUND ERROR: Expected a ConfigJSONObject but found ConfigJSONScalar. You are trying to get an item from a scalar as if it was an object. item=split [line=1;col=30]
```
=> Fix missing .value for NotAction

parliament/__init__.py, tests/unit/test_resource_formatting.py
I opened this for discussion.  Empty segments seem to be correctly evaluated now.  I added the tests individually because I wanted them all to run.  Let me know what you think.  I can compress the tests together after your comfortable that this does not break anything else.
=> Fix ARN validation where empty segments were always considered valid

parliament/policy.py
`jsoncfg` objects do not define a `node_exists` method, but they [override `__getattr__` with `__getitem__ `](https://github.com/pasztorpisti/json-cfg/blob/master/src/jsoncfg/config_classes.py#L285). This results in `self.policy_json.node_exists` not erroring out but returning a `ValueNotFoundNode` (because `jsoncfg` never raises key errors) and that for some reason [overrides `__call__`](https://github.com/pasztorpisti/json-cfg/blob/master/src/jsoncfg/config_classes.py#L155) with a method which ends up returning the first parameter passed.
TLDR, `self.policy_json.node_exists("Version")` would always return `"Version"`, hence passing the if-statement check. To fix this, it is simply enough to use the `jsoncfg.node_exists` utility function (which simply does a type check on the passed …
=> fix node_exists checks

README.md, parliament/__init__.py, parliament/statement.py
Analyzing a policy with an INVALID_ARN gives exceptions from all of the community auditors 
e.g.
```json
{
"Version":"2012-10-17",
"Statement":[
{
"Sid":"AddPerm",
"Effect":"Allow",
"Principal": "*",
"Action":["ssm:PutParameter"],
"Resource":[{"Fn::Sub": "arn:aws:ssm:*:${AWS::AccountId}:*"}]
}
]
}
```
from [test_resources.py](https://github.com/duo-labs/parliament/blob/c7ea5b25c4b279036fbe773ecb179c9667ba66ea/tests/unit/test_resources.py#L12-L23)
Also:
* Update managed policies repo link to @z0ph's
* Fix some spelling
=> Stop more checks if invalid resources are found

parliament/statement.py
The primary use case of this change is for faster developer feedback. If there are two typo'd Actions in a single IAM Statement, parliament will only catch one; the user then makes a fix and then re-runs parliament to find the second issue. If there is a serious Exception with the Action syntax, we should still bail out and return False. However, UnknownAction and UnknownPrefix are recoverable and parliament should attempt to find all of them.
Here's a sample case that demonstrates the problem:
```
{
"Version": "2012-10-17",
"Statement": [
{
"Action": [
"cloudwatch:DescribeAlxarms",
"elasticloadbalancing:DescribeRules",
"cloudwatch:GetMetricDataForAccounts",
"aaa:bbb",
"logs:DescribeMetricFilters",
"waf-regional:GetWebACLForResource"
],
"Resource": "*",
"Effect": "Allow"
}
]
}
``` …
=> Statement: Find all unknown Actions and unknown Prefixes in a Statement

parliament/community_auditors/advanced_policy_elements.py, parliament/community_auditors/config_override.yaml, parliament/community_auditors/tests/test_advanced_policy_elements.py
This auditor validates two AWS policy elements, and gives the user feedback to align with AWS documentation best practices. `NotResource` and `NotAction` are difficult to write policies for correctly because they implicitly `Allow` access to everything that is not specified in the Statement, and then revoke access.
I chose to make these 1 PR because they are both considered "advanced" policy elements by AWS and using either with `'Effect': 'Allow'`are both explicitly discouraged in the documentation. However, `NotResource` is targeted towards identity-based policies, whereas `NotAction` is targeted towards resource-based policies and trust relationships. So, I would be open to splitting this up somehow, e.g. by putting the checks into different community auditors Py files. Or, if we …
=> Validate use of NotResource and NotAction based on AWS best practices

parliament/cli.py
This fixes the syntax for json-cfg when running --aws-managed-policies and --auth-details-file
Before this commit you would get an error similar to the following:
jsoncfg.config_classes.JSONConfigNodeTypeError: Expected a ConfigJSONObject but found
ConfigJSONScalar. You are trying to access the __contains__ magic method of a scalar
config object.
It seems that instead of treating the json-cfg objects as hash's you're supposed to access keys
via attributes and use a method call when you want to convert it back into it's original form.
Passing an argument to this method call sets the default return, acting similar to:
obj.get('key', default)
=> Fix json-cfg syntax

parliament/misc.py
With large data sets, there were nodes created there did not exist.  Adding code to defend against that when creating the list.
=> Defense coding around non existent nodes

parliament/__init__.py, tests/unit/test_resource_formatting.py
* When checking a bucket arn the presence of a / was flagged as not a
match.  Because bucket resource arns can contain variables which in
turn can contain / (e.g. ["arn:aws:s3:::bucket/${aws:PrincipalTag/department}"])
as seen https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_variables.html#policy-vars-wheretouse
this is a false flag.
* This change removes the variables from the arn before checking the
presence of a /
* Also updates variable removal code from is_arn_strictly_valid which
did not account for a /
* Fixes #146
=> Removes variables from arn when checking buckets

parliament/cli.py
* Add ability to read from  stdin for a policy to be analyzed such as `cat file.json | parliament`
* Adds new FileType argument to read from stdin and don't allow both --file and stdin
* Implements #163
=> Add stdin support for reading policy

parliament/config.yaml
Instead of MALFORMED
(GitHub web UI added the newline, but no objections there.)
=> Change RESOURCE_STAR group to NOT_IDEAL

parliament/cli.py
In version 1.4.1 the --directory flag causes parliament to hang. There was a code change to make the default option for --file to be sys.stdin, making args.file always evaluate truthy. Since the args.file flag check comes before the args.directory check, the directory option is never used when specified.
This change adds a condition to the args.file path the only executes it when args.directory is not specified.
fixes #198
=> use file option only when directory is not used

parliament/community_auditors/config_override.yaml, parliament/community_auditors/single_value_condition_too_permissive.py, parliament/community_auditors/tests/test_single_value_condition_too_permissive.py
As per [this help article](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_single-vs-multi-valued-condition-keys.html) they "can lead to overly permissive policies"
=> Add check for using condition set operators with single-valued condition keys

parliament/config.yaml, parliament/statement.py, tests/unit/test_patterns.py
This check warns users when the combined scope of all Resource specifiers effectively spans "*". We infer this check by seeing if there is a wildcard Resource for every service that could possibly be manipulated by the statement Actions.
It's still straightforward to circumvent this check by adding a partition or an AWS account ID. Another way to circumvent this check is by "expanding" a single Resource specifier into 3 separate partition identifiers.
I didn't put this in community_auditors since it seemed closely linked to RESOURCE_STAR, however, I also didn't make this RESOURCE_STAR because that check is for explicit "*" and can be associated with a particular Action (whereas this check applies to the intersection of all Actions).
Fixes #106
=> Add RESOURCE_EFFECTIVELY_STAR check

parliament/policy.py
Give a list of str rather than a list of PosixPath
On Python 3.9.5:
```
>>> import email
>>> email.__path__
['/Users/kevinhock/.pyenv/versions/3.9.5/lib/python3.9/email']
>>> email.__path__[0]
'/Users/kevinhock/.pyenv/versions/3.9.5/lib/python3.9/email'
>>> type(email.__path__[0])
<class 'str'>
```
The [pkgutil.iter_modules](https://docs.python.org/3/library/pkgutil.html#pkgutil.iter_modules) docs are pretty bad on this:
`path should be either None or a list of paths to look for modules in.`
it doesn't specify string.
You can see a lot of other OSS projects have had bugs like this:
- https://github.com/n1ngu/faker/commit/c37017643327d30033112e8dd837046a8c740ed7
- https://github.com/simongrest/farm-pin-crop-detection-challenge/issues/2
etc.
Stack trace for posterity was:
```
File …
```
=> :bug: Fix pkgutil.iter_modules call

parliament/community_auditors/credentials_exposure.py
The 'cognito-idp:DescribeUserPoolClient' API action includes OAuth Client Secrets in it's response, so although the action doesn't return AWS credentials, should this be something that gets flagged for credentials exposure?
=> Add additional action to credentials exposure community auditor

utils/update_iam_data.py
The AWS endpoint has started to respond with a 405 Not Allowed and a CAPTCHA verification for the default user agent when requesting the data, at least when calling from GitHub Actions. Using a realistic user agent seems to combat this.
=> Add a realistic user-agent to avoid WAF for util

README.md
I'm not sure if I'm being too verbose, but I'm inspired by the fact that we don't have examples in the docs on how to use private auditors as a library nor having custom folder as discussed here: https://github.com/duo-labs/parliament/issues/88. In that case, I had no option, but to go to the source code to figure it out how I can do it.
This PR adds:
Docs on how to use private auditors in a custom folder:
- From the CLI
- As a library inside python code
=> Docs on private auditors custom folder

parliament/cli.py, setup.py
Hi!
This merge request implements a `--files` command-line argument that allows passing a list of policies to analyse.
The signature of the `main()` function was also modified to get `argv` as an argument, instead of assuming `sys.argv`.
Both changes are necessary to implement a `pre-commit` hook I’ve been using locally.
I may make the repository public if this patch is merged, for the sake of further contributing!
=> feat(cli): Support --files
